apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk
spec:
  version: 8.12.2
  nodeSets:
    # 3 dedicated master nodes
    - name: master
      count: 3
      config:
        node.roles: ["master"]
        #node.remote_cluster_client: false
    # 3 ingest-data nodes
    - name: ingest-data
      count: 3
      config:
        node.roles: ["data", "ingest"]
