all:
  hosts:
    kmaster:
      ansible_host: 192.168.84.54
      ip: 192.168.84.54
      access_ip: 192.168.84.54
    kworker1:
      ansible_host: 192.168.84.51
      ip: 192.168.84.51
      access_ip: 192.168.84.51
    kworker2:
      ansible_host: 192.168.84.52
      ip: 192.168.84.52
      access_ip: 192.168.84.52
#    kworker3:
#      ansible_host: 192.168.84.53
#      ip: 192.168.84.53
#      access_ip: 192.168.84.53
  children:
    kube_control_plane:
      hosts:
        kmaster:
    kube_node:
      hosts:
        kworker1:
        kworker2:
        #kworker3:
    etcd:
      hosts:
        kmaster:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
