- name: Custom installations for MNS
  hosts: kube_control_plane
  gather_facts: False
  become: true
  tasks:
    - name: Add NFS subdir external provisioner Helm repo
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        binary_path: "{{ bin_dir }}/helm"
        repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    - name: Install NFS subdir external provisioner using Helm
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner-default
        binary_path: "{{ bin_dir }}/helm"
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: default
        values:
          nfs:
            server: dev-newsan.mns.intra-mns.mu
            path: /DEV_NFS_DATA
          storageClass:
            name: nfs-new
            defaultClass: true

    - name: Add Traefik Helm repo
      kubernetes.core.helm_repository:
        name: traefik
        binary_path: "{{ bin_dir }}/helm"
        repo_url: https://traefik.github.io/charts
    - name: Install NFS subdir external provisioner using Helm
      kubernetes.core.helm:
        name: traefik
        binary_path: "{{ bin_dir }}/helm"
        chart_ref: traefik/traefik
        release_namespace: traefik
        values:
          dashboard:
            enabled: true
            domain: traefik.intra-mns.mu
            auth:
              basic:
                admin: $2y$05$kpCJY2gJWlgG5CUs5tdPx.2xGJ4xyqhWtjiiM/NKfHmj3pfUPsap2
          ssl:
            enabled: true
            enforced: true
            permanentRedirect: true
            generateTLS: true
            defaultCN: "*intra-mns.mu"
          service:
            externalIPs: [ 192.168.84.181 ]


