- name: Custom installations for MNS
  hosts: kmaster
  gather_facts: False
  become: true
  tasks:
    - name: Install NFS subdir external provisioner using Helm
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner-default
        binary_path: "{{ bin_dir }}/helm"
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: default
        values:
          nfs.server: dev-newsan.mns.intra-mns.mu
          nfs.path: /DEV_NFS_DATA
          storageClass.name: nfs-new
          storageClass.defaultClass: true

- name: Custom installations for MNS
  hosts: kube_control_plane[0]
  gather_facts: no
  roles:
    - name: helm-apps
      releases:
        - name: nfs-subdir-external-provisioner-default
          namespace: default
          chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
      repositories: "{{ repos }}"
        - name: simple-app
          url: "https://blog.leiwang.info/simple-app"
      release_common_opts: "{{ helm_params }}"
        wait_timeout: "5m"
