- name: Custom installations for MNS
  hosts: kube-master
  become: true
  tasks:
    - name: Add NFS subdir external provisioner Helm repo
      community.kubernetes.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

    - name: Install NFS subdir external provisioner using Helm
      community.kubernetes.helm:
        name: nfs-subdir-external-provisioner-default
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: default
        values:
          nfs.server: dev-newsan.mns.intra-mns.mu
          nfs.path: /DEV_NFS_DATA
          storageClass.name: nfs-new
          storageClass.defaultClass: true
