- name: Custom installations for MNS
  hosts: kmaster
  gather_facts: False
  become: true
  tasks:
    - name: Install NFS subdir external provisioner using Helm
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner-default
        binary_path: "{{ bin_dir }}/helm"
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: default
        values:
          nfs.server: dev-newsan.mns.intra-mns.mu
          nfs.path: /DEV_NFS_DATA
          storageClass.name: nfs-new
          storageClass.defaultClass: true
