- name: Custom installations for MNS
  hosts: kube_control_plane
  gather_facts: False
  become: true
  tasks:
    - name: Add NFS subdir external provisioner Helm repo
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        binary_path: "{{ bin_dir }}/helm"
        repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    - name: Install NFS subdir external provisioner using Helm
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner-default
        binary_path: "{{ bin_dir }}/helm"
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        release_namespace: default
        values:
          nfs:
            server: dev-newsan.mns.intra-mns.mu
            path: /DEV_NFS_DATA
          storageClass:
            name: nfs-new
            defaultClass: true

